### ISSUE TITLE
Language not adapted

### ISSUE THREAD

**Issue by Rom1-GoPlay** [adityar224/FlutterMarkdownEditor#5]
**Describe the bug**
The app is neither in my language nor in english. My android phone is set in french but when I open the app: 
![ScreenshotMarkDownApp.jpg](https://github.com/adityar224/FlutterMarkdownEditor/assets/131159819/b0ca7a1d-2299-4ad8-9efc-29bca84f5f4f)

**To Reproduce**
1. Download the app from the playstore
2. Open the app

**Expected behavior**
Get the same beautiful design but with text in my language or in english

**Screenshots**
See: "describe the bug".

**Desktop (please complete the following information):**
 not tried on desktop

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy A51]
 - OS: [Android 13]
 - Markdown Editor Version [1.1.0]

**Additional context**
This application seems amazing !

**Comment by Rom1-GoPlay** [comment]
I found a solution.
By adding english in the phone language settings. Now when I open the app everything is english.

But maybe some people will not have the idea... So I don't know if it is an issue.

**Comment by adityar224** [comment]
Thanks for pointing this out. The default language is supposed to be English. My guess is that since there are no French translations it went ahead and chose Arabic as a default language (Probably because alphabetical order xD). I'll look into this before the next update 👍

**Comment by adityar224** [comment]
Have added French translation too 👍
