### ISSUE TITLE
Cannot open files in the file manager

### ISSUE THREAD

**Issue by xuangeyouneihan** [adityar224/FlutterMarkdownEditor#8]
**Describe the bug**
I can only open markdown files inside the software. When I try to open the file in the file manager, the software tells me that I should try to open the file in the software.

**To Reproduce**
1. Locate the markdown file
2. Click on the file
3. Select "Markdown Editor"

**Expected behavior**
The editor opens the file successfully

**Screenshots**
![Screenshot_2023-09-12-14-42-05-636_android](https://github.com/adityar224/FlutterMarkdownEditor/assets/50788434/109971e8-ad21-4dbb-b06a-3152ab30c568)
![Screenshot_2023-09-12-14-29-44-050_com adeeteya markdown_editor](https://github.com/adityar224/FlutterMarkdownEditor/assets/50788434/5d551568-e1f9-46a3-b2c9-876a5504eb84)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi K50 Pro
 - OS: MIUI 14 (Android 13)
 - Browser: [Lemur Browser](https://lemurbrowser.com), a Chrome-based browser for Android that supports extensions
 - Version: 1.2.0

**Additional context**
My file manager is [Material Files](https://github.com/zhanghai/MaterialFiles) and my ROM is MIUI 14 (Android 13). I don't know whether the problem is caused by this software, file manager or OS.

**Comment by adityar224** [comment]
This is an issue with the built-in file manager. It works with external file managers please try opening with them.
